### ISSUE TITLE
Cannot query field "service" on type "Query". Did you mean "_service"?

### ISSUE THREAD

**Issue by renepardon** [movio/bramble#120]
Implementing a federated service subgraph based on the official spec https://www.apollographql.com/docs/federation/federation-spec/ results in bramble error from title above.

I just gave it a quick try locally:

```bash
docker run --net="host" -v $(pwd)/config.json:/config.json ghcr.io/movio/bramble
```

with a config.json which contains two services listed on my local machine:

```json
{
  "services": ["http://localhost:8010/graphql", "http://localhost:8020/graphql"]
}

```

I saw https://movio.github.io/bramble/#/getting-started?id=preparing-your-services-for-federation but this does not respect the official spec.

**Comment by nmaquet** [comment]
Bramble doesn't implement Apollo Federation. This is intentional. Instead, Bramble provides a slightly less powerful but much simpler mechanism to achieve the same goal. 

I'm not sure what you mean by 'official' spec. The Apollo Federation spec is published by Apollo at apollographql.com. In contrast, the official GraphQL spec is published by the GraphQL Foundation at graphql.org.
