### ISSUE TITLE
Support for ID sharding

### ISSUE THREAD

**Issue by phifty** [movio/bramble#45]
Hi,

first, thanks for the great work on this project!

I wonder if there is a way to implement sharding with this? We'd like a way (maybe via a plugin?) to map an ID to a shard number. A query of the ID would than end up at the service that is configured under that shard number. Are there any plans on this? Is there already way how I can implement it myself?

Best regard

**Comment by nmaquet** [comment]
Hey @phifty,

Thanks for your suggestion! I don't think it would be a great fit for Bramble to support this. It can't really be done as a plugin since plugins operate on a per-request basis and your suggested behaviour would need to route different requests to different services. I would recommend keeping the sharding concern one layer below Bramble in your architecture.
